### ISSUE TITLE
Error resolving dependency provider

### ISSUE THREAD

**Issue by fermino** [ypsu/pkgtrim#1]
Hey! I just found your package through the AUR, it's an awesome idea :)

I'm trying to debug the following message, I'm guessing it's due to some stale dependency info in my system (I'm carrying an installation from ~3 years ago); but I'm a bit lost.
```
$ pkgtrim
Error: load packages: resolve mypaint-brushes1: no provider found for dependency libmypaint<2.
```
I'm heading to compile it and try to understand how it all works, and will keep it updated in this issue. 
Thanks :)

**Comment by ypsu** [comment]
Oops, I didn't have a package with a max version constraint so I missed that case. Should be fixed now. I might have missed some other corner cases too. We'll see.

**Comment by ypsu** [comment]
Thanks for the report, btw. Note this tool currently completely ignores versions. It will get some deps wrong. I might add better version tracking later if people actually use this and care about getting such details right.

If you still are still seeing issues, could you send me your whole pacman database? You can dump it like this:

```
for f in /var/lib/pacman/local/*/desc; do echo "== $f"; cat "$f"; done >/tmp/pacman.textar
```

Upload it somewhere (some online paste tool or maybe here in github). Then I should be able to debug it like this:

```
pkgtrim -testfs=/tmp/pacman.textar
```

**Comment by fermino** [comment]
Thank you!! I updated it and now it works just fine :)
